build:
  stage: build
  only:
    - master
  tags:
    - spring-cloud-k8s

  script:
    - mvn clean package -Dmaven.test.skip=true
    - DIST_JAR_PATH=`find . -iname "*.jar" -not -iname "*-sources.jar"`



